apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: container-registry
data:
#  REGISTRY_HTTP_TLS_CERTIFICATE: /certs/tls.crt
#  REGISTRY_HTTP_TLS_KEY: /certs/tls.key
  REGISTRY_AUTH: htpasswd
  REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
  REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd

